name: Create Closure Primer Jobs

on:
  workflow_dispatch:
    inputs:
      stgEnvironment:
        type: boolean
        required: true
        description: Deploy to STG
        options:
        - STG
      uatEnvironment:
        type: boolean
        required: true
        description: Deploy to UAT
        options:
        - UAT
      whfEnvironment:
        type: boolean
        required: true
        description: Deploy to WHF
        options:
        - WHF

