name: Create Closure Primer Jobs

on:
  workflow_dispatch:
    inputs:
      stgEnvironment:
        type: boolean
        required: true
        description: STG
      uatEnvironment:
        type: boolean
        required: true
        description: UAT
      whfEnvironment:
        type: boolean
        required: true
        description: WHF

jobs:
  parse-envs:
    name: Parse selected environment(s)
    runs-on: ubuntu-latest
    steps:
      - name: Parse environment selection(s)
        id: parser
        run: |
          MATRIX_PARAMS_COMBINATIONS='
              {"environment": "stg"},
              {"environment": "uat"},
              {"environment": "whf"},
          '
          echo ::set-output name=envPass::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
    outputs:
      envSelection: ${{ steps.parser.outputs.envPass }}

  env-test:
    environment: ${{ matrix.environment }}
    name: Environment test
    needs: parse-envs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.parse-envs.outputs.envSelection) }}
    steps:
      - name: Verify proper environment switching via matrix strategy
        id: env-verify
        run: |
          echo ${{ secrets.env }} >> log.txt
          echo ${{ secrets.one }} >> log.txt
          echo ${{ secrets.two }} >> log.txt
          echo ${{ secrets.three }} >> log.txt
          echo ""
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          path: log.txt
          name: log

