name: Create Closure Primer Jobs

on:
  workflow_dispatch:
    inputs:
      stgEnvironment:
        type: boolean
        required: true
        description: STG
      uatEnvironment:
        type: boolean
        required: true
        description: UAT
      whfEnvironment:
        type: boolean
        required: true
        description: WHF

