name: Create Closure Primer Jobs 2

on:
  workflow_dispatch:
    inputs:
      stgEnvironment:
        type: boolean
        required: true
        description: STG
      uatEnvironment:
        type: boolean
        required: true
        description: UAT
      whfEnvironment:
        type: boolean
        required: true
        description: WHF
        
jobs:
  parse-envs:
    name: Parse selected environment(s)
    runs-on: ubuntu-latest
    steps:
      - run: |
          envString=""
          if [[ ${{ github.event.inputs.stgEnvironment }} == false && ${{ github.event.inputs.uatEnvironment }} == false && ${{ github.event.inputs.whfEnvironment }} == false ]]
          then
            echo "No  environment selected - at least one environment must be selected from which to deploy"
            exit 1
          else
            if [[ ${{ github.event.inputs.stgEnvironment }} == true ]]
            then
              envString=$envString"stg "
            fi
            if [[ ${{ github.event.inputs.uatEnvironment }} == true ]]
            then
              envString=$envString"uat "
            fi
            if [[ ${{ github.event.inputs.whfEnvironment }} == true ]]
            then
              envString=$envString"whf "
            fi
          fi
          echo $envString
          envArray=($envString)
          echo {$envArray}
          for i in ${!envArray[@]}; do
            echo "element $i is ${envArray[$i]}"
          done
  upload-artifact:
    needs: parse-envs
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        environment:
    steps:
      - uses: actions/upload-artifact@v2
        with:
          path: "${{ github.workspace }}/log.txt"
          name: log.txt
