name: Create Closure Primer Jobs 2

on:
  workflow_dispatch:
    inputs:
      stgEnvironment:
        type: choice
        required: true
        description: STG
        options:
        - stg
      uatEnvironment:
        type: choice
        required: true
        description: UAT
        options:
        - uat
      whfEnvironment:
        type: choice
        required: true
        description: WHF
        options:
        - whf

jobs:
  parse-envs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat ${{ secrets.one }} >> log.txt
        
  upload-artifact:
    needs: parse-envs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ github.event.inputs.stgEnvironment }} ${{ github.event.inputs.uatEnvironment }} ${{ github.event.inputs.whfEnvironment }}
    steps:
      - uses: actions/upload-artifact@v2
        with:
          path: "${{ github.workspace }}/log.txt"
          name: log.txt
