name: Create Closure Primer Jobs 2

on:
  workflow_dispatch:
    inputs:
      stgEnvironment:
        type: boolean
        required: true
        description: STG
      uatEnvironment:
        type: boolean
        required: true
        description: UAT
      whfEnvironment:
        type: boolean
        required: true
        description: WHF


jobs:
  parse-envs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ github.event.inputs.stgEnvironment }} == false && ${{ github.event.inputs.uatEnvironment }} == false && ${{ github.event.inputs.whfEnvironment }} == false ]]; then
            echo "No  environment selected - at least one environment must be selected from which to deploy"
          if [[ ${{ github.event.inputs.stgEnvironment }} == true ]]; then
            cat "stg " >> $envString
          if [[ ${{ github.event.inputs.uatEnvironment }} == true ]]; then
            cat "uat " >> $envString
          if [[ ${{ github.event.inputs.whfEnvironment }} == true ]]; then
            cat "whf " >> $envString
          echo $envString
          else
            echo "No  environment selected - at least one environment must be selected from which to deploy"
          exit 0
  upload-artifact:
    needs: parse-envs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ github.event.inputs.stgEnvironment }} ${{ github.event.inputs.uatEnvironment }} ${{ github.event.inputs.whfEnvironment }}
    steps:
      - uses: actions/upload-artifact@v2
        with:
          path: "${{ github.workspace }}/log.txt"
          name: log.txt
