name: Regression Test

on:
  workflow_dispatch:
    inputs:
      effectiveDate:
        description: 'Enter effective date (yyyymmdd):'
        required: true
        default: '20200120'
      clusterStart:
        type: boolean
        description: 'Start cluster batch nodes?'
        default: 'true'
      clusterStop:
        type: boolean
        description: 'Shutdown cluster when test completes?'
        default: 'true'
      testEnvironment:
        description: 'Environment? (dev, fred, jeff, etc.) HINT: Where did you deploy your code changes? Personal environments must be stored as a repo secret (<env>_regression_env). '
        required: false
        default: 'dev'
      nodesPerZone:
        description: 'How many nodes per zone? Note: If clusterStart == false, make sure this matches ACTUAL nodesPerZone.'
        required: false
        default: '1'
      createBaseline:
        type: boolean
        description: 'Use this run to generate & store all baseline outputs for this effective date?'
        required: false
        default: 'false'
      maxTolerance:
        description: 'The maximum absolute tolerance allowed for numeric comparisons during regression testing:'
        required: false
        default: '0.04'
      restartStep:
        type: choice
        description: 'Resume from step:'
        required: false
        default: 'n/a'
        options:
        - n/a
        - TRAIN_START
        - CLUSTER_START
        - TRAINING_MONITOR
        - FVA_START
        - FVA_MONITOR
        - FVA_COMPARE
        - FVT_START
        - FVT_MONITOR
        - FVT_COMPARE
        - PA_START
        - PA_MONITOR
        - PA_COMPARE
        - SIM_START
        - SIM_MONITOR
        - SIM_COMPARE
        - BASELINE_CREATE
        - CLUSTER_STOP
jobs:
  gollum:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::[{\"go\":\"1.13\",\"commit\":\"v1.0.0\"},{\"go\":\"1.14\",\"commit\":\"v1.2.0\"}]"
        
  gandolf:
    needs: gollum
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        cfg: 
          - ${{fromJson(needs.gollum.outputs.matrix)}}
    steps:
    - run: |
        echo bin-${{ matrix.cfg.go }}-${{ matrix.cfg.commit }}
        
  runner:
    needs: [gollum,gandolf]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: 
          - ${{fromJson(needs.gollum.outputs.matrix)}}
        client:
          - ${{fromJson(needs.gollum.outputs.matrix)}}
    steps:
    - run: |
          echo ${{ matrix.server.go }}-${{ matrix.server.commit }}
          echo ${{ matrix.client.go }}-${{ matrix.client.commit }}
