  
name: Create Closure Primer Jobs

on:
  workflow_dispatch:
    inputs:
      stgEnvironment:
        type: boolean
        required: true
        description: STG
  env-test:
    environment: ${{ matrix.environment }}
    name: Environment test
    needs: parse-envs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [uat, whf, stg]
    steps:
      - name: Verify proper environment switching via matrix strategy
        id: env-verify
        run: |
          cat ${{ secrets.env }} >> ${{ matrix.environment }}.txt
          cat ${{ secrets.one }} >> ${{ matrix.environment }}.txt
          cat ${{ secrets.two }} >> ${{ matrix.environment }}.txt
          cat ${{ secrets.three }} >> ${{ matrix.environment }}.txt
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.environment }}.txt
          name: ${{ matrix.environment }}
