name: Testing Passing Matrices

on:
  workflow_dispatch:
  
jobs:
  gollum:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::[{\"go\":\"1.13\",\"commit\":\"v1.0.0\"},{\"go\":\"1.14\",\"commit\":\"v1.2.0\"}]"
        
  gandolf:
    needs: gollum
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        cfg: 
          - ${{fromJson(needs.gollum.outputs.matrix)}}
    steps:
    - run: |
        echo bin-${{ matrix.cfg.go }}-${{ matrix.cfg.commit }}
        
  runner:
    needs: [gollum,gandolf]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: 
          - ${{fromJson(needs.gollum.outputs.matrix)}}
        client:
          - ${{fromJson(needs.gollum.outputs.matrix)}}
    steps:
    - run: |
          echo ${{ matrix.server.go }}-${{ matrix.server.commit }}
          echo ${{ matrix.client.go }}-${{ matrix.client.commit }}
